FORMAT: 1A
HOST: http://localhost:8000/absencies

# gestor_absencies

Gestor Absencies blablabla

## Teams [/teams]

### List All Teams [GET]

+ Response 200 (application/json)

        {
            "count": 2,
            "next": null,
            "previous": null,
            "results": [
                {
                    "name": "Team Rocket"
                }
            ]
        }
